spring.application.name=medical-service
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/medical_db}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.defer-datasource-initialization=true
spring.sql.init.schema-locations=classpath:db/*.sql
spring.sql.init.data-locations=classpath:db/*.sql
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never
jwt.expiration-ms=900000
jwt.secret=${JWT_KEY}
server.port=7070
spring.cache.type=redis
payment.service.url=${PAYMENT_URL}
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.data.redis.host=${SPRING_REDIS_HOST:localhost}
