spring.application.name=medical-service

# Datasource
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/medical_db}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=none

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

# JWT
jwt.expiration-ms=900000
jwt.secret=${JWT_KEY}

# Server
server.port=7070

# Redis
spring.cache.type=redis
spring.data.redis.host=${SPRING_REDIS_HOST:localhost}

# Kafka
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

# Payment
payment.service.url=${PAYMENT_URL}
