spring.application.name=payment-service
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/payment_db}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.defer-datasource-initialization=true
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never
stripe.key=${STRIPE_KEY}
stripe.webhook=${STRIPE_WEBHOOK_SECRET}
server.port=8082
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
